<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="modelo.modelo_tests.TestFindMethods-20160209185301" tests="3" time="0.138">
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testfind" time="0.023"/>
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testsave" time="0.097"/>
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testrepr" time="0.019">
		<error message="'str' object has no attribute 'id'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/sebastian/proyectos/SiGeSt/src/unittest/python/modelo/modelo_tests.py", line 30, in testrepr
    %(result.id, result.descripcion))
AttributeError: 'str' object has no attribute 'id'

Stdout:
Error en Select.
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[Error en Select.
No se encontro
Error en Select.
El Articulo se elimino correctamente.
Error en Select.
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
