<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="modelo.modelo_tests.TestDeposito-20160213194929" tests="3" time="0.032">
	<testcase classname="modelo.modelo_tests.TestDeposito" name="test1_save_try" time="0.020"/>
	<testcase classname="modelo.modelo_tests.TestDeposito" name="test2_save_except" time="0.008"/>
	<testcase classname="modelo.modelo_tests.TestDeposito" name="test3_find" time="0.004">
		<error message="find() takes 1 positional argument but 2 were given" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/sebastian/proyectos/SiGeSt/src/unittest/python/modelo/modelo_tests.py", line 83, in test3_find
    result = self.depMock.find(self.idDep)
TypeError: find() takes 1 positional argument but 2 were given
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
