<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="modelo.modelo_tests.TestFindMethods-20160213133131" tests="3" time="0.104">
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testrepr" time="0.001"/>
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testsave" time="0.090"/>
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testfind" time="0.014">
		<failure message="&quot;Articulo('n', 'n')&quot; != &quot;'No se encontro'&quot;
- Articulo('n', 'n')
+ 'No se encontro'
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/sebastian/proyectos/SiGeSt/src/unittest/python/modelo/modelo_tests.py", line 32, in testfind
    self.assertEqual(repr(expected), repr(result))
AssertionError: "Articulo('n', 'n')" != "'No se encontro'"
- Articulo('n', 'n')
+ 'No se encontro'

]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
