<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="modelo.modelo_tests.TestFindMethods-20160209185348" tests="3" time="0.113">
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testfind" time="0.021"/>
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testsave" time="0.075"/>
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testrepr" time="0.018">
		<error message="'str' object has no attribute 'id'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/sebastian/proyectos/SiGeSt/src/unittest/python/modelo/modelo_tests.py", line 31, in testrepr
    %(result.id, result.descripcion))
AttributeError: 'str' object has no attribute 'id'

Stdout:
No se encontro
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[No se encontro
El Articulo se elimino correctamente.
No se encontro
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
