<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="modelo.modelo_tests.TestFindMethods-20160213103345" tests="2" time="0.068">
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testrepr" time="0.001"/>
	<testcase classname="modelo.modelo_tests.TestFindMethods" name="testsave" time="0.067">
		<failure message="Articulo('n', 'n') != Articulo('n', 'n')" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/sebastian/proyectos/SiGeSt/src/unittest/python/modelo/modelo_tests.py", line 21, in testsave
    self.assertEqual(self.artMock.find(self.idArt), result)
AssertionError: Articulo('n', 'n') != Articulo('n', 'n')
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
